services:

  cleanup-logs:
    image: busybox
    command: sh -c "rm -rf /logs/*"
    volumes:
      - logs-data:/logs
  
  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=go_bank
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE_NAME=go_bank
      - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - logs-data:/logs
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=go_bank
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE_NAME=go_bank
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - TELEMETRY_TRACES_INTAKE_ENDPOINT=apm-server:8200
    depends_on:
      cleanup-logs:
        condition: service_completed_successfully
      migrator:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=go_bank
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U go_bank"]
      interval: 5s
      retries: 2
      start_period: 5s
      timeout: 3s

  redis:
    image: redis:7.4.0-alpine
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 5s
      retries: 2
      start_period: 5s
      timeout: 3s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4-arm64
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 2

  apm-server:
    image: docker.elastic.co/apm/apm-server:9.1.4-arm64
    ports:
      - "8200:8200"
    environment:
      - output.elasticsearch.hosts=["http://elasticsearch:9200"]
      - apm-server.otlp.enabled=true   # enable OTLP receiver
      - apm-server.otlp.http.enabled=true
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4-arm64
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.4-arm64
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.1.4-arm64
    user: root
    volumes:
      - logs-data:/logs
      - ./native-logs:/usr/share/filebeat/native-logs
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - api

  grafana:
    image: grafana/grafana:main
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  es-data:
  logs-data:
  prometheus-data:
  grafana-data: