logger:
  level: info # info, debug

server:
  port: 8080
  gracefulShutdownTimeoutInSeconds: 20

telemetry:
  serviceName: go-bank-api
  tracesIntakeEndpoint: localhost:8200 # host:port of the APM server; protocol is automatically added by the OpenTelemetry SDK 

database:
  postgres:
    host: localhost
    username: go_bank
    password: password
    databaseName: go_bank
    port: 5432
    options:
      caCertificate:
      maxOpenConnections: 20 # must always be less than ((number of servers) * (value of `max_connections` for the postgres instance))
      maxIdleConnections: 10 # must always be less than the value of maxOpenConnections
      connectionMaxLifetimeInSeconds: 300
      dialTimeoutInSeconds: 5
      readTimeoutInSeconds: 10
      writeTimeoutInSeconds: 10

cache:
  redis:
    host: localhost
    port: 6379
    password: password
    dbIndex: 0

auth:
  accessTokenExpiryDurationInSeconds: 900 # 15 mins (15 * 60 = 900 secs)
  accessTokenSecretSigningKey: abc123